Add more rules
sabinopa/password-validator pull request #3
Opened 2023-09-05 23:07 UTC by sabinopa

Processo de criacao de regras: 
  ok -  1.1 numero de caracteres
  ok -  1.2 presenca de letra maiuscula

2023-09-06 12:46 UTC, juliajubileu approved these changes
Aprovado!! :rocket: 

Próximos passos: 
1. fazer o merge desse Pull request 
![image](https://github.com/sabinopa/password-validator/assets/70206232/0baab01c-9132-4d3d-8c3c-854a24cb083e)


2. mudar para sua branch main no terminal `git checkout main`
3. atualizar sua branch com a versão remota `git pull`
4. abrir uma nova branch pra trabalhar em outras alterações `git checkout -b nome-da-branch-nova`

2023-09-06 16:59 UTC, juliajubileu requested changes
Só fazer essa pequena correção :)

2023-09-06 16:59 UTC, juliajubileu commented on ruby/password_validator.rb
> +  if letter.empty? || letters.none?{|char| char == char.upcase}
aqui precisa corrigir o nome da variável pra `letters`

2023-09-06 17:02 UTC, juliajubileu commented on ruby/password_validator.rb
> +  if letter.empty? || letters.none?{|char| char == char.upcase}
pra corrigir: 
1. entrar no repo local e acessar essa branch `git checkout add-more-rules`
2. fazer a correção e salvar o arquivo
3. adicionar a alteração `git add ruby/password_validator.rb`
4. fazer o commit `git  commit -m "correção de typo"`
5. subir a  correção pra essa branch remota `git push origin add-more-rules`

2023-09-08 11:43 UTC, sabinopa commented on ruby/password_validator.rb
> +  if letter.empty? || letters.none?{|char| char == char.upcase}
fiz :) acho que deu certo!

2023-09-08 12:10 UTC, juliajubileu commented on ruby/password_validator.rb
> +  if letter.empty? || letters.none?{|char| char == char.upcase}
supeeerrrrr

2023-09-08 12:15 UTC, juliajubileu approved these changes
Aprovado!! 🚀

Próximos passos:

1. fazer o merge desse Pull request 
![image](https://github.com/sabinopa/password-validator/assets/70206232/19dd47ed-75d3-466a-b223-de19abd4b50a)

2. mudar para sua branch main no terminal `git checkout main`
3. atualizar sua branch com a versão remota `git pull`
4. abrir uma nova branch pra trabalhar em outras alterações `git checkout -b nome-da-branch-nova`

2023-09-08 18:10 UTC, merged